apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: atlas
  region: ap-south-1

managedNodeGroups:
  - name: master-nodes
    labels: { role: master }
    instanceType: c5.large
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      publicKeyPath: ~/.ssh/AWS-EKS-Public-key.pub
    tags:
      nodegroup-role: master

  - name: data-nodes
    labels: { role: data }
    instanceType: i3.xlarge
    desiredCapacity: 2
    volumeSize: 40
    ssh:
      publicKeyPath: ~/.ssh/AWS-EKS-Public-key.pub
    tags:
      nodegroup-role: data

  - name: client-nodes
    labels: { role: client }
    instanceType: i3.xlarge
    desiredCapacity: 1
    volumeSize: 40
    ssh:
      publicKeyPath: ~/.ssh/AWS-EKS-Public-key.pub
    tags:
      nodegroup-role: client 
